name: build

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    - name: Swift Lint
      run: swiftlint --strict
    - name: Test iOS
      run: |
        xcodebuild build -scheme RealityUI -destination "platform=iOS Simulator,name=iPhone 14" | xcpretty
    - name: Test macOS
      run: |
        xcodebuild build -scheme RealityUI -destination "platform=macOS" | xcpretty
      env:
        SCHEME: RealityUI
